opentestbed:
  mqtt_broker:
    address: argus.paris.inria.fr
    port: 1883
  token: 123

6tisch:
  link_layer_key:
    index: 1
    value: ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff
  prefix: '2001:0DB8::'
